name: Tests Application
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  unit-test:
    name: Unit test on ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: -> Decode the keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEY_JKS }}
    - name: -> Relocate the keystore file
      run: cp ${{steps.decode_keystore.outputs.filePath}} android/
    - name: -> Setup Flutter environment
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
    - name: -> Check the environment
      run: flutter doctor -v
    - name: -> Install dependencies
      run: flutter pub get
    # - name: -> Analyze the source code
    #   run: flutter analyze
    # - name: -> Unit test
    #   run: flutter test
    - name: -> Generate apk file
      env:
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: flutter build apk --release
    - uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk